Stok_Takip/Stok_Takip/Models/StockSave.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stok_Takip.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class StockSave
    {
        public int ID { get; set; }
        [Display(Name = "Urun Adi")]
        public string ProductName { get; set; }
        [Display(Name = "Urun Kodu")]
        public string ProductCode { get; set; }
        [Display(Name = "Urun Aciklama")]
        public string ProductInfo { get; set; }
        [Display(Name = "Urun Adet")]
        public string ProductNumber { get; set; }
        [Display(Name = "Urun Ucret")]
        public string ProductPayment { get; set; }
    }
}

Stok_Takip/Stok_Takip/Controllers/StockSavesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stok_Takip.Models;

namespace Stok_Takip.Controllers
{
    public class StockSavesController : Controller
    {
        private StockEntities db = new StockEntities();

        // GET: StockSaves
        public ActionResult Index()
        {
            return View(db.StockSave.ToList());
        }

        // GET: StockSaves/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StockSave stockSave = db.StockSave.Find(id);
            if (stockSave == null)
            {
                return HttpNotFound();
            }
            return View(stockSave);
        }

        // GET: StockSaves/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StockSaves/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ProductName,ProductCode,ProductInfo,ProductNumber,ProductPayment")] StockSave stockSave)
        {
            if (ModelState.IsValid)
            {
                db.StockSave.Add(stockSave);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(stockSave);
        }

        // GET: StockSaves/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StockSave stockSave = db.StockSave.Find(id);
            if (stockSave == null)
            {
                return HttpNotFound();
            }
            return View(stockSave);
        }

        // POST: StockSaves/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ProductName,ProductCode,ProductInfo,ProductNumber,ProductPayment")] StockSave stockSave)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stockSave).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(stockSave);
        }

        // GET: StockSaves/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StockSave stockSave = db.StockSave.Find(id);
            if (stockSave == null)
            {
                return HttpNotFound();
            }
            return View(stockSave);
        }

        // POST: StockSaves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StockSave stockSave = db.StockSave.Find(id);
            db.StockSave.Remove(stockSave);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Stok_Takip/Stok_Takip/Views/StockSaves/Create.cshtml
@model Stok_Takip.Models.StockSave

@{
    ViewBag.Title = "Create";
}

<h2>Yeni Kayıt</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductInfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductInfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductInfo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPayment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-danger" /> |
                @Html.ActionLink("Anasayfaya Dön", "Index", "StockSaves", null, new { @class = " btn btn-warning" })
            </div>
        </div>
    </div>
}

Stok_Takip/Stok_Takip/Views/StockSaves/Delete.cshtml
@model Stok_Takip.Models.StockSave

@{
    ViewBag.Title = "Delete";
}

<h2>Kayıt Sil</h2>

<h3>Silmek İstediğinize Eminmisiniz?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPayment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-danger" /> |
            @Html.ActionLink("Anasayfaya Dön", "Index", "StockSaves", null, new { @class = " btn btn-warning" })
        </div>
    }
</div>

Stok_Takip/Stok_Takip/Views/StockSaves/Details.cshtml
@model Stok_Takip.Models.StockSave

@{
    ViewBag.Title = "Details";
}

<h2>Detaylar</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPayment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPayment)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit","StockSaves", new { id = Model.ID },new { @class = "btn btn-danger" }) |
    @Html.ActionLink("Anasayfaya Dön", "Index", "StockSaves", null, new { @class = " btn btn-warning" })
</p>

Stok_Takip/Stok_Takip/Views/StockSaves/Edit.cshtml
@model Stok_Takip.Models.StockSave

@{
    ViewBag.Title = "Edit";
}

<h2>Duzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductInfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductInfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductInfo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPayment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPayment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPayment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-danger" /> |
                @Html.ActionLink("Anasayfaya Dön", "Index", "StockSaves", null, new { @class = " btn btn-warning" })
            </div>
        </div>
    </div>
}

Stok_Takip/Stok_Takip/Views/StockSaves/Index.cshtml
@model IEnumerable<Stok_Takip.Models.StockSave>

@{
    ViewBag.Title = "Index";
}

<h2>Anasayfa</h2>

<p>
    @Html.ActionLink("Yeni Kayıt", "Create", "StockSaves", null, new { @class = " btn btn-warning" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductInfo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductPayment)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductInfo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductPayment)
        </td>
        <td>
            @Html.ActionLink("Duzenle", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Detaylar", "Details", new { id=item.ID }) |
            @Html.ActionLink("Sil", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>